# Generated by Django 3.0.4 on 2020-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=5000)),
                ('post_title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date field')),
            ],
        ),
    ]
