# Generated by Django 3.0.5 on 2020-04-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
        ('posts', '0002_auto_20200425_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stream',
            field=models.ForeignKey(db_column='title', default=None, on_delete=django.db.models.deletion.CASCADE, to='streams.Stream'),
        ),
    ]
