# Generated by Django 2.2.7 on 2020-04-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('duties', '0001_initial'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fblink', models.URLField(blank=True, max_length=300, null=True)),
                ('following', models.ManyToManyField(blank=True, null=True, to='users.User')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='posts.Post')),
                ('streams', models.ManyToManyField(blank=True, null=True, through='duties.Duty', to='streams.Stream')),
            ],
        ),
    ]
