# Generated by Django 3.0.5 on 2020-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200413_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.ManyToManyField(related_name='tokens', to='users.User')),
            ],
        ),
    ]
